### ISSUE TITLE
[REQUEST] Code for GC results analysis

### ISSUE THREAD

**Issue by yuxinwang1988** [Diet-Microbiome-Interactions-Lab/KitchenSink#2]
Hi, I have been doing a lot of SCFA analysis using the GC. When I do the data analysis, I have to copy and paste each value and then scroll down to the next. It takes a lot of time to do this repeating work. It would be lovely If there is a code that can help extract all the values for the SCFA. Thank you!

**Comment by wintermutant** [comment]
Thanks for bringing this up - I think this is a common task. I've got a python script I can cleanup and share to this repo. I'll get back to you once I finish and push to the repo

**Comment by wintermutant** [comment]
Hi @yuxinwang1988, please see #4 , which I merged into the main branch. There's a folder called /Chromatorgraphy, along with a readme file in there that will show you how to run it!
